import React,{useState}from 'react';
import{signIn}from 'next-auth/react';
import{useRouter}from 'next/router';
import Link from 'next/link';
export default function RegisterPage(){
  const router=useRouter();
  const[form,setForm]=useState({name:'',email:'',password:'',confirm:''});
  const[loading,setLoading]=useState(false);
  const[error,setError]=useState('');
  const set=(k:keyof typeof form)=>(e:React.ChangeEvent<HTMLInputElement>)=>setForm(p=>({...p,[k]:e.target.value}));
  const handleSubmit=async(e:React.FormEvent)=>{e.preventDefault();if(form.password!==form.confirm){setError('Senhas não coincidem');return;}if(form.password.length<8){setError('Senha deve ter ao menos 8 caracteres');return;}setLoading(true);setError('');try{const res=await fetch('/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:form.name,email:form.email,password:form.password})});const json=await res.json();if(!res.ok||!json.success)throw new Error(json.error?.message??'Erro ao criar conta');await signIn('credentials',{email:form.email,password:form.password,redirect:false});router.push('/');}catch(e){setError((e as Error).message);}finally{setLoading(false);}};  
  const inputStyle={width:'100%',padding:'10px 14px',background:'var(--card)',border:'1px solid var(--border)',borderRadius:8,color:'var(--text)',fontSize:13,outline:'none',boxSizing:'border-box' as const};
  return(<div style={{minHeight:'100vh',background:'var(--bg)',display:'flex',alignItems:'center',justifyContent:'center',padding:24}}><div style={{width:'100%',maxWidth:420}}><div style={{textAlign:'center',marginBottom:36}}><div style={{width:52,height:52,borderRadius:14,background:'linear-gradient(135deg,#00D4FF,#7C4DFF)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:22,margin:'0 auto 16px',color:'#090B0F',fontWeight:900}}>Q</div><h1 style={{fontSize:26,fontWeight:900,color:'var(--text)',letterSpacing:'-0.02em'}}>Criar conta</h1><p style={{fontSize:13,color:'var(--text-muted)',marginTop:6}}>Comece gratuitamente, sem cartão</p></div><form onSubmit={handleSubmit} style={{display:'flex',flexDirection:'column',gap:14}}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><div><label style={{fontSize:12,color:'var(--text-muted)',display:'block',marginBottom:6}}>Nome</label><input style={inputStyle} type="text" placeholder="Seu nome" value={form.name} onChange={set('name')} /></div><div><label style={{fontSize:12,color:'var(--text-muted)',display:'block',marginBottom:6}}>Email</label><input style={inputStyle} type="email" placeholder="seu@email.com" value={form.email} onChange={set('email')} required /></div></div><div><label style={{fontSize:12,color:'var(--text-muted)',display:'block',marginBottom:6}}>Senha</label><input style={inputStyle} type="password" placeholder="Mínimo 8 caracteres" value={form.password} onChange={set('password')} required /></div><div><label style={{fontSize:12,color:'var(--text-muted)',display:'block',marginBottom:6}}>Confirmar</label><input style={inputStyle} type="password" placeholder="Repita a senha" value={form.confirm} onChange={set('confirm')} required /></div>{error&&<div style={{background:'var(--red-dim)',border:'1px solid rgba(255,61,87,.3)',borderRadius:8,padding:'10px 14px',fontSize:13,color:'var(--red)'}}>{error}</div>}<button type="submit" disabled={loading} style={{padding:'12px',background:loading?'var(--border)':'var(--accent)',color:loading?'var(--text-muted)':'var(--bg)',border:'none',borderRadius:8,fontSize:14,fontWeight:700,cursor:'pointer',marginTop:4}}>{loading?'Criando...':'Criar conta grátis'}</button></form><div style={{textAlign:'center',marginTop:20}}><Link href="/auth/login" style={{fontSize:13,color:'var(--accent)',fontWeight:600}}>← Já tem conta? Entrar</Link></div></div></div>);
}