import React,{useState,useMemo}from 'react';
import{AreaChart,Area,LineChart,Line,BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer}from 'recharts';
import type{HistoricalDataPoint}from '../../types';
type Period='1W'|'1M'|'3M'|'6M'|'1Y';
function sma(v:number[],p:number):(number|null)[]{return v.map((_,i)=>i<p-1?null:+(v.slice(i-p+1,i+1).reduce((s,x)=>s+x,0)/p).toFixed(2));}
const TT=({active,payload,label}:any)=>{if(!active||!payload?.length)return null;const d=payload[0]?.payload;return(<div style={{background:'var(--card)',border:'1px solid var(--border)',borderRadius:8,padding:'10px 14px',fontSize:12}}><div style={{fontSize:11,color:'var(--text-muted)',marginBottom:6}}>{label}</div>{payload.map((p:any,i:number)=>(<div key={i} style={{display:'flex',justifyContent:'space-between',gap:16}}><span style={{color:p.color,fontSize:11}}>{p.name}</span><span style={{fontWeight:700,fontFamily:'var(--mono)',fontSize:12}}>{typeof p.value==='number'?p.value.toLocaleString('pt-BR',{minimumFractionDigits:2}):p.value}</span></div>))}{d?.volume&&<div style={{marginTop:6,paddingTop:6,borderTop:'1px solid var(--border)',fontSize:11,color:'var(--text-muted)'}}>Vol: {(d.volume/1e6).toFixed(1)}M</div>}</div>);};
export function PriceChart({data,ticker,color,height=280,showVolume=true,showMA=true,compact=false}:{data:HistoricalDataPoint[];ticker:string;color?:string;height?:number;showVolume?:boolean;showMA?:boolean;compact?:boolean}){
  const[period,setPeriod]=useState<Period>('3M');
  const PERIODS:Record<Period,number>={'1W':7,'1M':30,'3M':90,'6M':180,'1Y':365};
  const filtered=useMemo(()=>data.slice(-PERIODS[period]),[data,period]);
  const enriched=useMemo(()=>{const cs=filtered.map(d=>d.close);const m20=sma(cs,20);const m50=sma(cs,50);return filtered.map((d,i)=>({...d,ma20:m20[i],ma50:m50[i]}));},[filtered]);
  const pos=enriched.length>1?enriched[enriched.length-1].close>=enriched[0].close:true;
  const lc=color??(pos?'var(--green)':'var(--red)');
  const gid='g'+ticker.replace(/[^a-z0-9]/gi,'');
  if(!data.length)return<div style={{height,display:'flex',alignItems:'center',justifyContent:'center',color:'var(--text-muted)',fontSize:13}}>Sem dados</div>;
  return(<div>{!compact&&<div style={{display:'flex',gap:6,marginBottom:12}}>{(['1W','1M','3M','6M','1Y']as Period[]).map(p=><button key={p} onClick={()=>setPeriod(p)} style={{padding:'4px 10px',borderRadius:6,background:period===p?'var(--accent)':'transparent',color:period===p?'var(--bg)':'var(--text-muted)',border:`1px solid ${period===p?'var(--accent)':'var(--border)'}`,fontSize:11,fontWeight:700,cursor:'pointer'}}>{p}</button>)}</div>}
  <ResponsiveContainer width="100%" height={height}><AreaChart data={enriched} margin={{top:5,right:0,bottom:0,left:0}}><defs><linearGradient id={gid} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={lc} stopOpacity={0.25}/><stop offset="100%" stopColor={lc} stopOpacity={0}/></linearGradient></defs>{!compact&&<CartesianGrid stroke="var(--border)" strokeDasharray="4 4" vertical={false}/>}<XAxis dataKey="date" tick={{fill:'var(--text-muted)',fontSize:10}} tickLine={false} axisLine={false} interval={Math.floor(enriched.length/6)}/><YAxis tick={{fill:'var(--text-muted)',fontSize:10}} tickLine={false} axisLine={false} width={64} tickFormatter={v=>v.toLocaleString('pt-BR',{maximumFractionDigits:0})} domain={['auto','auto']}/><Tooltip content={<TT/>}/><Area type="monotone" dataKey="close" name="Preço" stroke={lc} strokeWidth={2} fill={`url(#${gid})`} dot={false}/>{showMA&&<><Line type="monotone" dataKey="ma20" name="MA20" stroke="var(--accent)" strokeWidth={1.5} dot={false} strokeDasharray="5 3" connectNulls/><Line type="monotone" dataKey="ma50" name="MA50" stroke="var(--purple)" strokeWidth={1.5} dot={false} strokeDasharray="5 3" connectNulls/></>}</AreaChart></ResponsiveContainer>
  {showVolume&&!compact&&<ResponsiveContainer width="100%" height={48} style={{marginTop:4}}><BarChart data={enriched} margin={{top:0,right:0,bottom:0,left:0}}><XAxis dataKey="date" hide/><YAxis hide/><Bar dataKey="volume" name="Volume" fill="var(--accent)" opacity={0.3} radius={[2,2,0,0]}/></BarChart></ResponsiveContainer>}</div>);}